// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wykiazoqcnfmzhycovxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5a2lhem9xY25mbXpoeWNvdnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1ODI4ODksImV4cCI6MjA2MjE1ODg4OX0.bFA5X8hs7FZnVFsN_Sj35Zc4l2cS3Z6n2oSPjUCgod4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);