// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbrdctohwwrgnusehffe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5icmRjdG9od3dyZ251c2VoZmZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTk3MjQsImV4cCI6MjA2NDQzNTcyNH0.95oyzzJP_WbN6oLuZSuH7UJd6VkogTzQVmqbpoW2YDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);